import { describe, it } from 'node:test'
import { expect } from '@std/expect'
import { parse as parseCsvMatrix } from '@std/csv/parse'
import { CsvParseError, parseCsv, parseCsvBytes } from './mod.ts'
describe('CSV parsing', () => {
	const fixtures = new URL('./fixtures/', import.meta.url)
	async function readFixture(path: string): Promise<Uint8Array> {
		return await Deno.readFile(new URL(path, fixtures))
	}
	it('parseCsvBytes detects supported delimiters and byte encodings', async () => {
		const comma = parseCsvBytes(
			await readFixture('representative/hubspot/companies-export.csv'),
		)
		const semicolon = parseCsvBytes(
			await readFixture('edge-cases/semicolon-delimited.csv'),
		)
		const tab = parseCsvBytes(await readFixture('edge-cases/tab-delimited.tsv'))
		const bom = parseCsvBytes(
			await readFixture('edge-cases/utf8-bom-non-ascii.csv'),
		)
		const legacy = parseCsvBytes(
			new Uint8Array([
				0x43,
				0x61,
				0x66,
				0xe9,
				0x2c,
				0x44,
				0x6f,
				0x6d,
				0x61,
				0x69,
				0x6e,
				0x0a,
				0x41,
				0x63,
				0x6d,
				0xe9,
				0x2c,
				0x61,
				0x63,
				0x6d,
				0x65,
				0x2e,
				0x65,
				0x78,
				0x61,
				0x6d,
				0x70,
				0x6c,
				0x65,
			]),
		)
		expect(comma.delimiter).toEqual(',')
		expect(semicolon.delimiter).toEqual(';')
		expect(tab.delimiter).toEqual('	')
		expect(bom.encoding).toEqual('utf-8-bom')
		expect(legacy.encoding).toEqual('windows-1252')
		expect(
			legacy.diagnostics.some((diagnostic) => diagnostic.code === 'legacy-encoding'),
		).toBeTruthy()
	})
	it('parseCsvBytes preserves logical rows and identifies an instructional preamble', async () => {
		const multiline = parseCsvBytes(
			await readFixture('edge-cases/multiline-quotes-and-commas.csv'),
		)
		const pipedrive = parseCsvBytes(
			await readFixture('official/pipedrive-sample-official.csv'),
		)
		expect(multiline.rows.length).toEqual(2)
		expect(multiline.rows[0]?.values.some((value) => value.includes('\n')))
			.toBeTruthy()
		expect(pipedrive.headerRow > 1).toBeTruthy()
		expect(
			pipedrive.diagnostics.some((diagnostic) => diagnostic.code === 'preamble-skipped'),
		).toBeTruthy()
	})
	it('parseCsv disambiguates headers and preserves source cells as strings', async () => {
		const duplicate = parseCsvBytes(
			await readFixture('edge-cases/duplicate-and-empty-headers.csv'),
		)
		const identifiers = parseCsvBytes(
			await readFixture('edge-cases/leading-zero-identifiers.csv'),
		)
		const formulas = parseCsvBytes(
			await readFixture('edge-cases/formula-injection.csv'),
		)
		expect(new Set(duplicate.columns.map((column) => column.key)).size).toEqual(
			duplicate.columns.length,
		)
		expect(
			duplicate.diagnostics.some((diagnostic) => diagnostic.code === 'blank-header'),
		).toBeTruthy()
		expect(
			duplicate.diagnostics.some((diagnostic) => diagnostic.code === 'duplicate-header'),
		).toBeTruthy()
		expect(identifiers.rows[0]?.values.some((value) => /^0\d+/.test(value)))
			.toBeTruthy()
		expect(
			formulas.rows.flatMap((row) => row.values).some((value) => value.startsWith('=')),
		).toBeTruthy()
		expect(
			formulas.diagnostics.some((diagnostic) => diagnostic.code === 'spreadsheet-formula'),
		).toBeTruthy()
		expect(
			formulas.rows.some((row) =>
				row.diagnostics.some((diagnostic) => diagnostic.code === 'spreadsheet-formula')
			),
		).toBeTruthy()
	})
	it('parseCsv supports explicit dialect and header-row overrides', () => {
		const document = parseCsv(
			[
				'Generated by CRM',
				'Company;Domain',
				'Northstar;northstar.example',
			].join('\n'),
			{ delimiter: ';', headerRow: 2 },
		)
		expect(document.headerRow).toEqual(2)
		expect(document.delimiter).toEqual(';')
		expect(document.rows[0]?.values).toEqual(['Northstar', 'northstar.example'])
	})
	it('parseCsv enforces caller-owned safety limits', () => {
		expect(() =>
			parseCsv('Company,Domain\nOne,one.example\nTwo,two.example', {
				maxRows: 1,
			})
		).toThrow(CsvParseError)
		expect(() => parseCsv('Company,Domain\nOne,one.example', { maxColumns: 1 }))
			.toThrow(CsvParseError)
		expect(() =>
			parseCsv('Company,Domain\nNorthstar,northstar.example', {
				maxCellLength: 5,
			})
		).toThrow(CsvParseError)
	})
	it('parseCsvBytes rejects empty and malformed input', async () => {
		const empty = await readFixture('edge-cases/empty-file.csv')
		const malformed = await readFixture(
			'edge-cases/malformed-unclosed-quote.csv',
		)

		expect(() => parseCsvBytes(empty)).toThrow(CsvParseError)
		expect(() => parseCsvBytes(malformed)).toThrow(CsvParseError)
	})
	it('all supplied fixtures match their expected acceptance outcome', async () => {
		const matrix = parseCsvMatrix(
			await Deno.readTextFile(new URL('validation.csv', fixtures)),
			{ skipFirstRow: true },
		) as Record<string, string>[]
		expect(matrix.length).toEqual(41)
		for (const fixture of matrix) {
			const path = fixture.path
			const expected = fixture.expected_outcome
			if (!path || !expected) {
				throw new Error('Fixture matrix rows require path and expected_outcome.')
			}
			let error: unknown
			try {
				parseCsvBytes(await readFixture(path), { fileName: path })
			} catch (cause) {
				error = cause
			}
			if (expected === 'reject') {
				expect(error instanceof CsvParseError).toBeTruthy()
			} else {
				expect(error).toEqual(undefined)
			}
		}
	})
	it('parseCsv enforces source limits before structural parsing', () => {
		expect(() =>
			parseCsvBytes(
				new TextEncoder().encode('Company,Domain\nNorthstar,northstar.example'),
				{ maxBytes: 8 },
			)
		).toThrow(CsvParseError)
		expect(() =>
			parseCsv('Company,Domain\nNorthstar,northstar.example', {
				maxCharacters: 8,
			})
		).toThrow(CsvParseError)
	})
	it('parseCsv merges caller aliases with the default mapping policy', () => {
		const document = parseCsv(
			'Legal Entity,Primary Host\nNorthstar,northstar.example',
			{
				headerAliases: {
					company: ['Legal Entity'],
					domain: ['Primary Host'],
				},
			},
		)
		expect(document.columns.map(({ role }) => role)).toEqual([
			'company',
			'domain',
		])
		expect(
			parseCsv('Company,Domain\nNorthstar,northstar.example', {
				headerAliases: { domain: ['Primary Host'] },
			}).columns.map(({ role }) => role),
		).toEqual(['company', 'domain'])
	})
})
