// @generated by scripts/schema.ts. DO NOT EDIT.
// Zod schemas are the runtime source of truth. Regenerate with `deno task schema`.

export type PathType = string;

export type AdapterNameType = string;

export type EntryKindType = "file" | "directory";

export type OpfsContextType = "window" | "dedicated-worker" | "shared-worker" | "service-worker" | "worker" | "unknown";

export type CoordinationModeType = "auto" | "web-locks" | "local" | "none";

export type WriteModeType = "replace" | "append" | "update";

export type SupportModeType = "native" | "emulated" | "partitioned" | "unsupported";

export type MetricsModeType = "none" | "basic" | "timing";

export type PartitionModeType = "never" | "auto" | "always";

export type AdapterPartitionType = {
  "mode": PartitionModeType;
  "partBytes": number;
  "thresholdBytes"?: number | undefined;
  "stream"?: boolean | undefined;
  "maxParts"?: number | undefined;
  "layout": string;
};

export type AdapterLimitsType = {
  "maxFileBytes"?: number | undefined;
  "maxValueBytes"?: number | undefined;
  "maxKeyBytes"?: number | undefined;
  "minPartBytes"?: number | undefined;
  "maxPartBytes"?: number | undefined;
  "maxParts"?: number | undefined;
  "maxConcurrency"?: number | undefined;
  "maxBatchBytes"?: number | undefined;
};

export type OptimizationType = {
  "streamRead": boolean;
  "streamWrite": boolean;
  "rangeRead": boolean;
  "nativeCopy": boolean;
  "nativeMove": boolean;
};

export type AdapterCapabilitiesType = {
  "read": boolean;
  "write": boolean;
  "streamRead": boolean;
  "streamWriteModes": readonly WriteModeType[];
  "rangeRead": boolean;
  "nativeCopy": boolean;
  "nativeMove": boolean;
  "positionalWrite": boolean;
  "syncAccess": boolean;
};

export type ErrorCodeType = "unavailable" | "not-found" | "already-exists" | "type-mismatch" | "invalid-path" | "invalid-operation" | "not-supported" | "locked" | "quota-exceeded" | "permission-denied" | "aborted" | "too-large" | "unknown";

export type RecordVersionType = 1;

export type DirectoryRecordType = {
  "version": RecordVersionType;
  "path": PathType;
  "parent": PathType;
  "name": string;
  "lastModified": number;
  "kind": "directory";
};

export type FileRecordType = {
  "version": RecordVersionType;
  "path": PathType;
  "parent": PathType;
  "name": string;
  "lastModified": number;
  "kind": "file";
  "data": string;
  "size": number;
  "mediaType": string;
};

export type RecordType = DirectoryRecordType | FileRecordType;

export type Db0DialectType = "mysql" | "postgresql" | "sqlite" | "libsql";

export type SqlIdentifierType = string;

export type DriverKindType = "file" | "record" | "object";

export type LimitKindType = "hard" | "policy" | "dynamic";

export type LimitSourceType = "provider" | "implementation" | "user" | "probe";

export type LimitUnitType = "bytes" | "count" | "milliseconds" | "operations";

export type LimitType = {
  "code": string;
  "kind": LimitKindType;
  "source": LimitSourceType;
  "unit": LimitUnitType;
  "value"?: number | undefined;
  "detail"?: string | undefined;
};

export type RequirementStateType = "available" | "missing" | "unknown";

export type RequirementType = {
  "code": string;
  "state": RequirementStateType;
  "reason"?: string | undefined;
};

export type DriverOwnershipType = "none" | "borrowed" | "owned";

export type DriverOptimizationType = {
  "code": string;
  "enabled": boolean;
  "changesBehavior": boolean;
  "disableable": boolean;
  "detail"?: string | undefined;
};

export type FileDriverCapabilitiesType = {
  "read": boolean;
  "write": boolean;
  "streamRead": boolean;
  "streamWriteModes": readonly WriteModeType[];
  "rangeRead": boolean;
  "copy": boolean;
  "move": boolean;
  "positionalWrite": boolean;
  "syncAccess": boolean;
};

export type RecordReplacementType = "atomic" | "best-effort" | "unknown";

export type RecordDriverCapabilitiesType = {
  "rangeRead": boolean;
  "streamRead": boolean;
  "write": boolean;
  "writeModes": readonly WriteModeType[];
  "streamWriteModes": readonly WriteModeType[];
  "replacement": RecordReplacementType;
  "binary": boolean;
  "transactions": boolean;
};

export type ObjectDriverCapabilitiesType = {
  "rangeRead": boolean;
  "streamRead": boolean;
  "streamWrite": boolean;
  "copy": boolean;
  "conditionalWrite": boolean;
  "multipart": boolean;
  "metadata": boolean;
  "versions": boolean;
};

export type RequestPolicyType = {
  "retries"?: number | undefined;
  "minDelayMs"?: number | undefined;
  "maxDelayMs"?: number | undefined;
  "multiplier"?: number | undefined;
  "jitter"?: number | undefined;
  "timeoutMs"?: number | false | undefined;
};

export type IntegrationDirectionType = {
  "supported": boolean;
  "reason"?: string | undefined;
};

export type IntegrationDirectionsType = {
  "toOpfs": IntegrationDirectionType;
  "fromOpfs": IntegrationDirectionType;
};

export type S3AddressingType = "path" | "virtual";

export type S3CredentialsType = {
  "accessKeyId": string;
  "secretAccessKey": string;
  "sessionToken"?: string | undefined;
};

export type AzureStorageVersionType = string;
