// @generated by scripts/schema.ts. DO NOT EDIT.
// Zod schemas are the runtime source of truth. Regenerate with `deno task schema`.

/** Structural output compiled from the runtime schema for `PathType`. */
export type PathType = string;

/** Structural output compiled from the runtime schema for `AdapterNameType`. */
export type AdapterNameType = string;

/** Structural output compiled from the runtime schema for `EntryKindType`. */
export type EntryKindType = "file" | "directory";

/** Structural output compiled from the runtime schema for `OpfsContextType`. */
export type OpfsContextType = "window" | "dedicated-worker" | "shared-worker" | "service-worker" | "worker" | "unknown";

/** Structural output compiled from the runtime schema for `CoordinationModeType`. */
export type CoordinationModeType = "auto" | "web-locks" | "local" | "none";

/** Structural output compiled from the runtime schema for `WriteModeType`. */
export type WriteModeType = "replace" | "append" | "update";

/** Structural output compiled from the runtime schema for `SupportModeType`. */
export type SupportModeType = "native" | "emulated" | "partitioned" | "unsupported";

/** Structural output compiled from the runtime schema for `MetricsModeType`. */
export type MetricsModeType = "none" | "basic" | "timing";

/** Structural output compiled from the runtime schema for `PartitionModeType`. */
export type PartitionModeType = "never" | "auto" | "always";

/** Structural output compiled from the runtime schema for `AdapterPartitionType`. */
export type AdapterPartitionType = {
  "mode": PartitionModeType;
  "partBytes": number;
  "thresholdBytes"?: number | undefined;
  "stream"?: boolean | undefined;
  "maxParts"?: number | undefined;
  "layout": string;
};

/** Structural output compiled from the runtime schema for `AdapterLimitsType`. */
export type AdapterLimitsType = {
  "maxFileBytes"?: number | undefined;
  "maxValueBytes"?: number | undefined;
  "maxKeyBytes"?: number | undefined;
  "minPartBytes"?: number | undefined;
  "maxPartBytes"?: number | undefined;
  "maxParts"?: number | undefined;
  "maxConcurrency"?: number | undefined;
  "maxBatchBytes"?: number | undefined;
};

/** Structural output compiled from the runtime schema for `OptimizationType`. */
export type OptimizationType = {
  "streamRead": boolean;
  "streamWrite": boolean;
  "rangeRead": boolean;
  "nativeCopy": boolean;
  "nativeMove": boolean;
};

/** Structural output compiled from the runtime schema for `AdapterCapabilitiesType`. */
export type AdapterCapabilitiesType = {
  "read": boolean;
  "write": boolean;
  "streamRead": boolean;
  "streamWriteModes": readonly WriteModeType[];
  "rangeRead": boolean;
  "nativeCopy": boolean;
  "nativeMove": boolean;
  "positionalWrite": boolean;
  "syncAccess": boolean;
};

/** Structural output compiled from the runtime schema for `ErrorCodeType`. */
export type ErrorCodeType =
  | "unavailable"
  | "not-found"
  | "already-exists"
  | "type-mismatch"
  | "invalid-path"
  | "invalid-operation"
  | "not-supported"
  | "locked"
  | "quota-exceeded"
  | "permission-denied"
  | "aborted"
  | "too-large"
  | "unknown";

/** Structural output compiled from the runtime schema for `RecordVersionType`. */
export type RecordVersionType = 1;

/** Structural output compiled from the runtime schema for `DirectoryRecordType`. */
export type DirectoryRecordType = {
  "version": RecordVersionType;
  "path": PathType;
  "parent": PathType;
  "name": string;
  "lastModified": number;
  "kind": "directory";
};

/** Structural output compiled from the runtime schema for `FileRecordType`. */
export type FileRecordType = {
  "version": RecordVersionType;
  "path": PathType;
  "parent": PathType;
  "name": string;
  "lastModified": number;
  "kind": "file";
  "data": string;
  "size": number;
  "mediaType": string;
};

/** Structural output compiled from the runtime schema for `RecordType`. */
export type RecordType = DirectoryRecordType | FileRecordType;

/** Structural output compiled from the runtime schema for `Db0DialectType`. */
export type Db0DialectType = "mysql" | "postgresql" | "sqlite" | "libsql";

/** Structural output compiled from the runtime schema for `SqlIdentifierType`. */
export type SqlIdentifierType = string;

/** Structural output compiled from the runtime schema for `DriverKindType`. */
export type DriverKindType = "file" | "record" | "object";

/** Structural output compiled from the runtime schema for `LimitKindType`. */
export type LimitKindType = "hard" | "policy" | "dynamic";

/** Structural output compiled from the runtime schema for `LimitSourceType`. */
export type LimitSourceType = "provider" | "implementation" | "user" | "probe";

/** Structural output compiled from the runtime schema for `LimitUnitType`. */
export type LimitUnitType = "bytes" | "count" | "milliseconds" | "operations";

/** Structural output compiled from the runtime schema for `LimitType`. */
export type LimitType = {
  "code": string;
  "kind": LimitKindType;
  "source": LimitSourceType;
  "unit": LimitUnitType;
  "value"?: number | undefined;
  "detail"?: string | undefined;
};

/** Structural output compiled from the runtime schema for `RequirementStateType`. */
export type RequirementStateType = "available" | "missing" | "unknown";

/** Structural output compiled from the runtime schema for `RequirementType`. */
export type RequirementType = {
  "code": string;
  "state": RequirementStateType;
  "reason"?: string | undefined;
};

/** Structural output compiled from the runtime schema for `DriverOwnershipType`. */
export type DriverOwnershipType = "none" | "borrowed" | "owned";

/** Structural output compiled from the runtime schema for `DriverOptimizationType`. */
export type DriverOptimizationType = {
  "code": string;
  "enabled": boolean;
  "changesBehavior": boolean;
  "disableable": boolean;
  "detail"?: string | undefined;
};

/** Structural output compiled from the runtime schema for `FileDriverCapabilitiesType`. */
export type FileDriverCapabilitiesType = {
  "read": boolean;
  "write": boolean;
  "streamRead": boolean;
  "streamWriteModes": readonly WriteModeType[];
  "rangeRead": boolean;
  "copy": boolean;
  "move": boolean;
  "positionalWrite": boolean;
  "syncAccess": boolean;
};

/** Structural output compiled from the runtime schema for `RecordReplacementType`. */
export type RecordReplacementType = "atomic" | "best-effort" | "unknown";

/** Structural output compiled from the runtime schema for `RecordDriverCapabilitiesType`. */
export type RecordDriverCapabilitiesType = {
  "rangeRead": boolean;
  "streamRead": boolean;
  "write": boolean;
  "writeModes": readonly WriteModeType[];
  "streamWriteModes": readonly WriteModeType[];
  "replacement": RecordReplacementType;
  "binary": boolean;
  "transactions": boolean;
};

/** Structural output compiled from the runtime schema for `ObjectDriverCapabilitiesType`. */
export type ObjectDriverCapabilitiesType = {
  "rangeRead": boolean;
  "streamRead": boolean;
  "streamWrite": boolean;
  "copy": boolean;
  "conditionalWrite": boolean;
  "multipart": boolean;
  "metadata": boolean;
  "versions": boolean;
};

/** Structural output compiled from the runtime schema for `RequestPolicyType`. */
export type RequestPolicyType = {
  "retries"?: number | undefined;
  "minDelayMs"?: number | undefined;
  "maxDelayMs"?: number | undefined;
  "multiplier"?: number | undefined;
  "jitter"?: number | undefined;
  "timeoutMs"?: number | false | undefined;
};

/** Structural output compiled from the runtime schema for `IntegrationDirectionType`. */
export type IntegrationDirectionType = {
  "supported": boolean;
  "reason"?: string | undefined;
};

/** Structural output compiled from the runtime schema for `IntegrationDirectionsType`. */
export type IntegrationDirectionsType = {
  "toOpfs": IntegrationDirectionType;
  "fromOpfs": IntegrationDirectionType;
};

/** Structural output compiled from the runtime schema for `S3AddressingType`. */
export type S3AddressingType = "path" | "virtual";

/** Structural output compiled from the runtime schema for `S3CredentialsType`. */
export type S3CredentialsType = {
  "accessKeyId": string;
  "secretAccessKey": string;
  "sessionToken"?: string | undefined;
};

/** Structural output compiled from the runtime schema for `AzureStorageVersionType`. */
export type AzureStorageVersionType = string;
